---
- name: Install and configure nginx
  hosts: nginx
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
      become: yes

    - name: Ensure /etc/nginx/conf.d directory exists
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Ensure Nginx is reloaded
      systemd:
        name: nginx
        state: reloaded
      when: true
