---
- name: Install and configure nginx
  hosts: nginx
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
      become: yes

    - name: Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Ensure Nginx is reloaded
      systemd:
        name: nginx
        state: reloaded
      when: true
