---
- name: Start Nginx
  hosts: nginx
  become: yes

  tasks:
    - name: Start Nginx service
      systemd:
        name: nginx
        state: started

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
