---
- name: Install and configure grafana
  hosts: grafana
  become: yes

  tasks:
    - name: Install Grafana
      yum:
        name: grafana
        state: present
      become: yes

    - name: Ensure Grafana is started and enabled
      systemd:
        name: grafana-server
        state: started
        enabled: yes
