---
- name: Install Grafana
  apt:
    name: grafana
    state: present
  become: yes

- name: Ensure Grafana is started and enabled
  systemd:
    name: grafana-server
    state: started
    enabled: yes
